name: fathom_dnd
description: A new Flutter project.
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state management
  stacked: ^2.1.7

  # navigation
  auto_route: ^3.2.3+1

  # inversion of control
  get_it: ^7.1.3
  injectable: ^1.4.1

  # firebase
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.8
  firebase_auth: ^3.3.7
  stacked_firebase_auth: ^0.2.10+2

  # misc
  logger: ^1.0.0
  google_fonts: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generators
  build_runner: ^2.0.4
  auto_route_generator: ^3.2.3
  injectable_generator: ^1.4.1
  flutter_launcher_icons: ^0.9.0

  # linting
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  # Assets Example
  assets:
    - assets/images/
    - google_fonts/
#
# Fonts Example
#  fonts:
#    - family: Open Sans
#      fonts:
#        - asset: assets/fonts/OpenSans-Italic.ttf
#          style: italic
#        - asset: assets/fonts/OpenSans-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/OpenSans-ExtraBold.ttf
#          weight: 800
#        - asset: assets/fonts/OpenSans-Light.ttf
#          weight: 300
#        - asset: assets/fonts/OpenSans-Regular.ttf
#          weight: 400
