// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx8RZ3fJGrfPO05Cl4ogPDW4FjZQepLfM',
    appId: '1:949219382945:web:dd0530ffd91a1d576182e0',
    messagingSenderId: '949219382945',
    projectId: 'fathom-dnd',
    authDomain: 'fathom-dnd.firebaseapp.com',
    storageBucket: 'fathom-dnd.appspot.com',
    measurementId: 'G-SWB7XE0CDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6WAk3lyejoK9WYkSWKgINlwJlsnaD7RQ',
    appId: '1:949219382945:android:5326c3c0bb2b767f6182e0',
    messagingSenderId: '949219382945',
    projectId: 'fathom-dnd',
    storageBucket: 'fathom-dnd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcxXqZfuVsQcC0Af1-pgDJyvmKHdfTB7c',
    appId: '1:949219382945:ios:e1708f4b6531aac26182e0',
    messagingSenderId: '949219382945',
    projectId: 'fathom-dnd',
    storageBucket: 'fathom-dnd.appspot.com',
    iosClientId: '949219382945-97qhjhcsvs80gdkm0sgdjuou51ulledo.apps.googleusercontent.com',
    iosBundleId: 'com.mukxdev.fathomdnd',
  );
}
